"""Supervised Training (Offline npz).

Loads .npz files generated by the data pipeline, provides
(channels, probs, masks) batches for supervised training.
"""
import os
import shutil
import subprocess
import sys
from datetime import datetime
from typing import Optional

import torch
import torch.optim as optim
from tqdm import tqdm

from config import TrainingConfig, ModelConfig
from training.trajectory_pool import TrajectoryPool
from training.utils import (
    build_model,
    compute_loss,
    model_forward,
    model_forward_logits,
    save_checkpoint,
)


def train_supervised(
    config: TrainingConfig,
    model_cfg: ModelConfig,
    device: Optional[str] = None,
    arch: str = "V5",
    run_dir: str = "",
):
    """Train the model offline using TrajectoryPool's batch()."""
    if not config.data_dir:
        raise ValueError(
            "Offline SUPERVISED mode strictly requires a valid 'data_dir' to load .npz files. "
            "Please specify it via CLI (e.g. --data_dir data) or ensure your config provides a default."
        )

    from utils.device import get_device
    device = get_device(device if device is not None else config.device)
        
    run_dir = run_dir or datetime.now().strftime("runs/%Y%m%d_%H%M%S")
    os.makedirs(run_dir, exist_ok=True)
    
    # Spawn background generator if needed
    os.makedirs(config.data_dir, exist_ok=True)
    log_file = os.path.join(config.data_dir, "data_gen.log")
    print(f"Starting background data generator (logs to {log_file})...")
    gen_cmd = [
        sys.executable, "scripts/generate_data.py",
        "--n_samples", str(config.n_games),
        "--output", config.data_dir,
        "--width", str(config.board_width),
        "--height", str(config.board_height),
        "--mines", str(config.board_mines),
        "--workers", "1"  # Use single-process writer to avoid file lock issues without UUID
    ]
    with open(log_file, "w") as f:
        subprocess.Popen(gen_cmd, stdout=f, stderr=f)
    
    # Initialize the unified TrajectoryPool for offline supervised mode
    # compute_probs=True so we have targets to distill
    pool = TrajectoryPool(
        board_width=config.board_width,
        board_height=config.board_height,
        board_mines=config.board_mines,
        pool_size=config.pool_size,
        pool_workers=config.pool_workers,
        data_dir=config.data_dir,
        mixed_mode=config.mixed_mode,
        compute_probs=True,
    )
    
    model = build_model(arch, model_cfg, device)
        
    if config.pretrained:
        print(f"Loading pretrained: {config.pretrained}")
        model.load_pretrained(config.pretrained, device=device)
        
    optimizer = optim.AdamW(model.parameters(), lr=config.learning_rate)
    
    print(f"Training on {device} - Offline SUPERVISED mode - Arch: {arch} - Loss: {config.loss_type}")
    print(f"Board Config: {config.board_width}x{config.board_height} with {config.board_mines} mines")
    print(f"Run dir: {run_dir}")

    # ── Loss setup ──────────────────────────────────────────────────────────
    target_type = "binary" if config.loss_type == "bce" else "probs"
    if config.loss_type == "bce":
        total_cells = config.board_width * config.board_height
        mines = config.board_mines
        pos_weight_val = (total_cells - mines) / max(mines, 1)
        print(f"BCE Loss with binary (ground-truth) targets, pos_weight={pos_weight_val:.2f}")
    else:
        pos_weight_val = None
        print("MSE Loss with solver probability targets (distillation)")
    
    # Calculate batches per epoch correctly based on states, not just games
    batch_size = getattr(config, 'batch_size', 64)
    estimated_states = config.n_games * 15
    batches_per_epoch = max(1, estimated_states // batch_size)
    print(f"Dataset: Target {config.n_games} games. Estimated {estimated_states} states -> {batches_per_epoch} batches/epoch")
        
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=batches_per_epoch * config.epochs, eta_min=config.min_lr
    )
    
    best_wr = 0.0
    
    for epoch in range(1, config.epochs + 1):
        pool.refresh()  # Pull in any newly generated data from disk!
        
        model.train()
        total_loss = 0.0
        
        pbar = tqdm(total=batches_per_epoch, desc=f"Epoch {epoch}/{config.epochs}")
        
        for _ in range(batches_per_epoch):
            # 1. Fetch batch from unified pool
            channels, targets, masks = pool.batch(batch_size, target_type=target_type)

            channels = channels.to(device)
            targets = targets.to(device)
            masks = masks.to(device)

            # 2. Forward pass. BCE uses raw logits; MSE uses probabilities.
            if config.loss_type == "bce":
                preds = model_forward_logits(
                    arch, model, channels, config.refinement_steps
                )
            else:
                preds = model_forward(arch, model, channels, config.refinement_steps)
            preds = preds[:, 0]  # (B, H, W)

            # 3. Loss
            loss = compute_loss(config.loss_type, preds, targets, masks, pos_weight_val, device)
            
            # 4. Backward
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip_norm)
            optimizer.step()
            scheduler.step()
            
            total_loss += loss.item()
            pbar.update(1)
            pbar.set_postfix({"loss": f"{loss.item():.4f}", "lr": f"{scheduler.get_last_lr()[0]:.1e}"})
            
        pbar.close()
        avg_loss = total_loss / batches_per_epoch
        print(f"Epoch {epoch} complete - Avg Loss: {avg_loss:.4f}")
        
        # Periodic Evaluation
        from training.evaluate import evaluate_model
        print(f"\n  ── Evaluating Epoch {epoch} ──")
        model.eval()
        eval_metrics = evaluate_model(
            model, device,
            n_games=config.eval_games,
            width=config.board_width,
            height=config.board_height,
            total_mines=config.board_mines,
            board_pool_path=config.board_pool_path,
            refine_steps=config.refinement_steps,
            quiet=False
        )
        wr = eval_metrics["win_rate"]
        
        # Save checkpoint with full metadata
        save_checkpoint(
            run_dir, f"model_ep{epoch}.pt",
            model, optimizer, model_cfg, config.loss_type, arch,
            epoch, wr, scheduler=scheduler,
        )
        
        if wr > best_wr:
            best_wr = wr
            shutil.copy2(os.path.join(run_dir, f"model_ep{epoch}.pt"), os.path.join(run_dir, "best_model.pt"))
            print(f"  🏆 New best model! Win rate: {best_wr:.1%}")
