"""Supervised MSE Training (Offline npz).

Loads .npz files generated by the data pipeline, provides
(channels, probs, masks) batches for supervised training.
"""
import os
import shutil
import time
from datetime import datetime
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import numpy as np
import torch
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm

from config import POLICY, TrainingConfig, TrainingMetrics, ModelConfig
from model.architecture import MinesweeperTransformer
from training.trajectory_pool import TrajectoryPool


def train_supervised(
    config: TrainingConfig,
    model_cfg: ModelConfig,
    device: str = "cuda" if torch.cuda.is_available() else "cpu",
    run_dir: str = "",
):
    """Train the model offline using TrajectoryPool's batch()."""
    run_dir = run_dir or datetime.now().strftime("runs/%Y%m%d_%H%M%S")
    os.makedirs(run_dir, exist_ok=True)
    
    # Initialize the unified TrajectoryPool for offline supervised mode
    # compute_probs=True so we have targets to distill
    pool = TrajectoryPool(
        board_width=config.board_width,
        board_height=config.board_height,
        board_mines=config.board_mines,
        pool_size=config.pool_size,
        pool_workers=config.pool_workers,
        data_dir=config.data_dir,
        mixed_mode=config.mixed_mode,
        compute_probs=True,
    )
    
    model = MinesweeperTransformer(model_cfg).to(device)
    optimizer = optim.AdamW(model.parameters(), lr=config.learning_rate)
    
    print(f"Training on {device} - Offline SUPERVISED mode")
    print(f"Run dir: {run_dir}")
    
    # Calculate rough number of batches per epoch (assuming n_games as total samples)
    batch_size = getattr(config, 'batch_size', 64)
    batches_per_epoch = max(1, config.n_games // batch_size)
    
    for epoch in range(1, config.epochs + 1):
        model.train()
        total_loss = 0.0
        
        pbar = tqdm(total=batches_per_epoch, desc=f"Epoch {epoch}/{config.epochs}")
        
        for _ in range(batches_per_epoch):
            # 1. Fetch batch from unified pool
            channels, targets, masks = pool.batch(batch_size)
            
            channels = channels.to(device)
            targets = targets.to(device)
            masks = masks.to(device)
            
            # 2. Forward pass
            preds, _ = model(channels)
            probs = preds[:, 0]  # (B, H, W)
            
            # 3. Compute loss (only on covered cells)
            loss = F.mse_loss(probs[masks], targets[masks])
            
            # 4. Backward
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip_norm)
            optimizer.step()
            
            total_loss += loss.item()
            pbar.update(1)
            pbar.set_postfix({"loss": f"{loss.item():.4f}"})
            
        pbar.close()
        avg_loss = total_loss / batches_per_epoch
        print(f"Epoch {epoch} complete - Avg Loss: {avg_loss:.4f}")
        
        # Save checkpoint
        ckpt_path = os.path.join(run_dir, f"model_ep{epoch}.pt")
        torch.save(model.state_dict(), ckpt_path)
        print(f"Saved checkpoint to {ckpt_path}")
